# Site settings
title: THUMT
email: thupretrainchnmed@163.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.
lang: zh-CN

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://thupcm.github.io # the base hostname & protocol for your site
git_address: https://github.com/thupcm/thupcm.github.io
git_edit_address: https://github.com/thupcm/thupcm.github.io/blob/master

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: aksakalli/jekyll-doc-theme@gh-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Asia/Hong_Kong
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
